<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schéma applicatif : partenaires, simulations, leads (SPEC §5).
 *
 * Le zonage lui-même (`rga_zone_*` et la vue `rga_zone_courante`) n'est PAS ici :
 * il est chargé par bin/charger-rga.sh depuis le shapefile officiel, et rechargé
 * à chaque nouveau millésime sans passer par une migration (SPEC §4.4).
 */
final class Version20260824084847 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma applicatif : partner, simulation, lead';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lead (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload JSON NOT NULL, statut VARCHAR(20) NOT NULL, tentatives SMALLINT NOT NULL, delivered_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, partner_id INT NOT NULL, simulation_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_289161CB9393F8FE ON lead (partner_id)');
        $this->addSql('CREATE INDEX IDX_289161CBFEC09103 ON lead (simulation_id)');
        $this->addSql('CREATE INDEX idx_lead_statut_delivered ON lead (statut, delivered_at)');
        $this->addSql('CREATE TABLE partner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, public_key VARCHAR(40) NOT NULL, nom VARCHAR(120) NOT NULL, actif BOOLEAN NOT NULL, origines_autorisees JSON NOT NULL, theme VARCHAR(40) DEFAULT NULL, lead_endpoint VARCHAR(255) DEFAULT NULL, lead_email VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_312B3E1666F9D463 ON partner (public_key)');
        $this->addSql('CREATE TABLE simulation (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lat NUMERIC(9, 6) NOT NULL, lon NUMERIC(9, 6) NOT NULL, code_insee VARCHAR(5) DEFAULT NULL, niveau_code SMALLINT DEFAULT NULL, converti BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, partner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBDA467B9393F8FE ON simulation (partner_id)');
        $this->addSql('CREATE INDEX idx_simulation_partner_date ON simulation (partner_id, created_at)');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CB9393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CBFEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE simulation ADD CONSTRAINT FK_CBDA467B9393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CB9393F8FE');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CBFEC09103');
        $this->addSql('ALTER TABLE simulation DROP CONSTRAINT FK_CBDA467B9393F8FE');
        $this->addSql('DROP TABLE lead');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE simulation');
    }
}
