<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Le lead ne transite plus par ce serveur (SPEC §6 et §9).
 *
 * Le widget redirige vers le formulaire du partenaire, pré-rempli par
 * paramètres d'URL. Aucune donnée personnelle ne touche cette base : la table
 * `lead` n'a plus d'objet, et avec elle disparaissent le chiffrement au repos,
 * la purge à J+30 et le statut de sous-traitant au sens de l'article 28.
 *
 * `partner.lead_champs` porte la correspondance entre nos noms logiques et les
 * champs du formulaire du partenaire — c'est ce qui garde le code générique.
 * `lead_email` servait de repli quand le relais échouait : il n'y a plus de
 * relais.
 */
final class Version20260824144919 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Redirection vers le formulaire du partenaire : suppression de la table lead';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT fk_289161cb9393f8fe');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT fk_289161cbfec09103');
        $this->addSql('DROP TABLE lead');
        // Défaut posé le temps de l'ajout, puis retiré : sans lui, l'ALTER
        // échoue sur les partenaires déjà en base. Le schéma final est bien
        // « NOT NULL sans défaut », conforme à ce qu'attend Doctrine.
        $this->addSql("ALTER TABLE partner ADD lead_champs JSON DEFAULT '{}' NOT NULL");
        $this->addSql('ALTER TABLE partner ALTER COLUMN lead_champs DROP DEFAULT');
        $this->addSql('ALTER TABLE partner DROP lead_email');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lead (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload JSON NOT NULL, statut VARCHAR(20) NOT NULL, tentatives SMALLINT NOT NULL, delivered_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, partner_id INT NOT NULL, simulation_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_lead_statut_delivered ON lead (statut, delivered_at)');
        $this->addSql('CREATE INDEX idx_289161cbfec09103 ON lead (simulation_id)');
        $this->addSql('CREATE INDEX idx_289161cb9393f8fe ON lead (partner_id)');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT fk_289161cb9393f8fe FOREIGN KEY (partner_id) REFERENCES partner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT fk_289161cbfec09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE partner ADD lead_email VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE partner DROP lead_champs');
    }
}
